version: '3'

services:
  debian:
    build: .
    image: develop/icecast
    container_name: icecast
    restart: unless-stopped
    ports:
     - 8000:8000
    environment:
      VIRTUAL_NETWORK: ${NETWORK}
      VIRTUAL_PORT: 8000
      VIRTUAL_HOST: stream.evin-record.dev
      LETSENCRYPT_HOST: stream.evin-record.dev
      LETSENCRYPT_EMAIL: admin@evin-record.dev
    networks:
      - default


networks:
  default:
    external:
      name: ${NETWORK}