version: '3'

services:
### MySQL Container #########################################
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    networks:
      - backend
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
      MYSQL_USER: homestead
      MYSQL_DATABASE: ${MYSQL_DATABASE:-homestead}

### Redis Container #########################################
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - backend
    volumes:
      - redis_volume:/data

### PHP Container ###########################################
  phpfpm:
    build: fpm
    container_name: phpfpm
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    volumes:
      - ${ROOT_PATH}/html:/var/www/html:rw
    environment:
      REDIS_HOST: redis
      MYSQL_HOST: mysql
      DB_NAME: ${MYSQL_DATABASE:-homestead}
      DB_DATABASE: ${MYSQL_DATABASE:-homestead}
      DB_PASSWORD: ${MYSQL_PASSWORD:-secret}

### Nginx Server Container ##################################
  app:
    build: app
    image: develop:app
    depends_on:
      - phpfpm
      - mysql
      - composer
    links:
      - phpfpm
      - mysql
      - composer
    container_name: app
    working_dir: /var/www/html
    restart: unless-stopped
    volumes:
      - ${ROOT_PATH}/html:/var/www/html/:ro
    networks:
      - frontend
      - backend
    environment:
      VIRTUAL_NETWORK: ${NETWORK}
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

### Composer Container ######################################
  composer:
    image: composer/composer:php7
    container_name: composer
    command: install
    volumes:
      - ${ROOT_PATH}/html:/app

### Node js Container ########################################
  node:
    image: node:8.1
    container_name: node
    command: bash -c "cd app && yarn install && npm run docker-up"
    volumes:
      - ${ROOT_PATH}/html:/app

networks:
  frontend:
    external:
      name: ${NETWORK}
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

volumes:
  mysql_volume:
    driver: local
  redis_volume:
      driver: local
